airflow:
  connections:
    - conn_id: open_meteo_api
      conn_type: http
      conn_host: api.open-meteo.com
      conn_schema: https
      conn_port: 
      conn_login: 
      conn_password: 
      conn_extra: 
  pools: []
  variables: []
